server:
  port: 8080

spring:
  application:
    name: e-procurer

cassandra:
  contact-points: localhost
  keyspace-name: ocds
  port: 9042
#  username: caclient
#  password: 6AH7vbrkMWnfK

ocds.prefix: ocds-t1s2t3